# -*- coding: utf-8 -*-
"""CAPSTONE PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QjtBAyo_f-nsKyoaLbaCf8SF4xQE0sQ
"""

# 1. IMPORT LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
!pip install streamlit
import streamlit as st
import pickle


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# UPLOADING DATASET & CLEANING
from google.colab import files
import io

print("Please upload 'data (3).csv'")
uploaded = files.upload()

# Read the uploaded file
if 'data (3).csv' in uploaded:
    data = pd.read_csv(io.BytesIO(uploaded['data (3).csv']))
    print("File loaded successfully!")
    display(data.head())
else:
    print("The uploaded file name does not match 'data (3).csv'. Please check the name and try again.")

data.head()

data.info()

data.describe()

data.isnull().sum()

data.drop_duplicates()

# 3. DATA PREPROCESSING
data['Gender'] = data['Gender'].map({'Male': 1, 'Female': 0})

data['Vehicle_Age'] = data['Vehicle_Age'].map({
    '< 1 Year': 0,
    '1-2 Year': 1,
    '> 2 Years': 2
})

data['Vehicle_Damage'] = data['Vehicle_Damage'].map({
    'Yes': 1,
    'No': 0
})
# remove id column
data = data.drop('id', axis=1)

# 4. FEATURING AND TARGETING
X = data.drop('Response', axis=1)
y = data['Response']

# 5. TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

# 6. TRAINING 3 MODELS ONE BY ONE
# Logistic Regression
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
lr_acc = accuracy_score(y_test, lr_pred)

print("Logistic Regression Accuracy:", lr_acc)

# Decision Tree
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
dt_acc = accuracy_score(y_test, dt_pred)

print("Decision Tree Accuracy:", dt_acc)

# Random Forest
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
rf_acc = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:", rf_acc)

# 8. MATPLOTLIB GRAPH
models = ['Logistic', 'Decision Tree', 'Random Forest']
accuracies = [lr_acc, dt_acc, rf_acc]

plt.bar(models, accuracies)
plt.xlabel("Models")
plt.ylabel("Accuracy")
plt.title("Accuracy Comparison")
plt.show()

# 9. SELECT BEST MODEL
best_model_name = models[np.argmax(accuracies)]

# Assign the actual model object to best_model based on its name
if best_model_name == 'Logistic':
    best_model = lr_model
elif best_model_name == 'Decision Tree':
    best_model = dt_model
elif best_model_name == 'Random Forest':
    best_model = rf_model

print("Best Model:", best_model_name)

# Save the best model
import pickle
pickle.dump(best_model, open("model.pkl", "wb"))
print(f"Best model '{best_model_name}' saved as model.pkl")

# 10. STREAMLIT WEB APP
import pickle
import streamlit as st

st.title("Insurance Claim Prediction")
age = st.slider("Enter Age", 18, 100)
premium = st.number_input("Enter Annual Premium")

# Load the best model
best_model = pickle.load(open("model.pkl", "rb"))

if st.button("Predict"):
    sample_data = [[
        1,          # Gender
        age,
        1,          # Driving License
        28,         # Region Code
        0,          # Previously Insured
        1,          # Vehicle Age
        1,          # Vehicle Damage
        premium,
        152,        # Sales Channel
        100         # Vintage
    ]]

    prediction = best_model.predict(sample_data)

    if prediction[0] == 1:
        st.success("Customer is likely to respond")
    else:
        st.error("Customer is not likely to respond")

"""**DEPLOYMENT**"""

import streamlit as st

#  STEP 1: CONFIGURATION
st.set_page_config(page_title="Insurance Prediction App")

#  STEP 2: DATA LOADING & PREPROCESSING
# Using a function with cache so it doesn't reload every time you move a slider
@st.cache_data
def load_and_clean_data():
    # Load the dataset
    df = pd.read_csv('data (3).csv')
  # Simple Preprocessing (Mapping strings to numbers)
    df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})
    df['Vehicle_Age'] = df['Vehicle_Age'].map({'< 1 Year': 0, '1-2 Year': 1, '> 2 Years': 2})
    df['Vehicle_Damage'] = df['Vehicle_Damage'].map({'Yes': 1, 'No': 0})

    # Drop ID as it's not a feature for prediction
    df = df.drop('id', axis=1)
    return df

try:
    data = load_and_clean_data()
except Exception as e:
    st.error(f"Error loading and cleaning data: {e}")

#  STEP 3: MODEL TRAINING
# We train the model here so the app is self-contained
from sklearn.preprocessing import StandardScaler

X = data.drop('Response', axis=1)
y = data['Response']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the data to help the model converge
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Using Logistic Regression as it performed best in our testing [cite: 150]
# Increased max_iter to address ConvergenceWarning
model = LogisticRegression(max_iter=2000)
model.fit(X_train_scaled, y_train)

#  STEP 4: STREAMLIT UI
st.title("Customer Insurance Prediction")
st.write("Enter the details below to check if a customer is likely to buy vehicle insurance.")

# Two-column layout for a neat look
col1, col2 = st.columns(2)

with col1:
    age = st.slider("Age", 18, 90, 30)
    gender = st.selectbox("Gender", ["Male", "Female"])
    driving_license = st.selectbox("Has Driving License?", ["Yes", "No"])
    region_code = st.number_input("Region Code", value=28)
    previously_insured = st.selectbox("Already Insured?", ["Yes", "No"])

with col2:
    v_age = st.selectbox("Vehicle Age", ["< 1 Year", "1-2 Year", "> 2 Years"])
    v_damage = st.selectbox("Ever Damaged Vehicle?", ["Yes", "No"])
    premium = st.number_input("Annual Premium Amount", value=30000)
    channel = st.number_input("Sales Channel ID", value=152)
    vintage = st.number_input("Days Associated (Vintage)", value=100)

# --- STEP 5: PREDICTION LOGIC
if st.button("Calculate Prediction"):
    # Convert UI inputs back to numeric format for the model
    input_data = [[
        1 if gender == "Male" else 0,
        age,
        1 if driving_license == "Yes" else 0,
        region_code,
        1 if previously_insured == "Yes" else 0,
        0 if v_age == "< 1 Year" else (1 if v_age == "1-2 Year" else 2),
        1 if v_damage == "Yes" else 0,
        premium,
        channel,
        vintage
    ]]

    prediction = model.predict(input_data)

    st.divider()
    if prediction[0] == 1:
        st.success("Result: The customer is INTERESTED in the insurance.")
    else:
        st.error("Result: The customer is NOT INTERESTED.")

try:
    pass
except FileNotFoundError:
    st.error("Please ensure 'data (3).csv' is in the same folder as this script.")

